### ISSUE TITLE
Speech Queue

### ISSUE THREAD

**Issue by victordibia** [ibmtjbot/tjbotlib#8]
Delibrate on how TJBot handles speech and queuing.
Currently any requests to speak are discarded if the bot is currently speaking. Upside is that the bot doesn't not start saying things that are no longer useful or important when a user has moved from from context.

**Comment by leandrodvd** [comment]
What I do in my code is to instead of speaking directly everything that comes, add it to a queue and have a "speak runner" that reads from that queue and speaks it on 200ms interval.

The problem with this is that sometimes the queue grows and, as you mentioned, the bot starts saying things that are no longer in context, like answering a question asked 30sec ago.

What I'm considering to do is to add a limit to that queue so that it ignores anything new when the queue is full, or maybe discard and replace the last element in the queue.
